TARGET      = rlm_smsotp
SRCS        = rlm_smsotp.c
HEADERS     = 
RLM_CFLAGS  = 
RLM_LIBS    = 
RLM_INSTALL = 

## this uses the RLM_CFLAGS and RLM_LIBS and SRCS defs to make TARGET.
include ../rules.mak

$(LT_OBJS): $(HEADERS)
